### ISSUE TITLE
Show a grid of people in the community page instead of a list

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#1]
Right now we only show the text containing the person's name in the [community list](https://code-with-ahsan.github.io/community-portfolio/people), and on the [person page](https://code-with-ahsan.github.io/community-portfolio/people/ahsanayaz).
We need to show the profile avatar as well as make it a grid of people. Just like we have for the projects inside a [person page](https://code-with-ahsan.github.io/community-portfolio/people/ahsanayaz).

Should be something like this
![image](https://user-images.githubusercontent.com/9844254/136655555-5f1fe067-2831-412a-9739-261029ee2e41.png)

**Comment by arsalan98m** [comment]
I will work on it assign this issue on me
