### ISSUE TITLE
In dark mode, the project card's background blends with the page background

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#23]
Expected:
In the dark mode, the card's background should have a lighter grey (visible)

Issue:
![image](https://user-images.githubusercontent.com/9844254/136655597-1755a3a4-22d3-4d1a-ba47-18efa241863a.png)

**Comment by Nabeelhassan** [comment]
Is this the desired output?
![image](https://user-images.githubusercontent.com/3646709/136674517-f050b530-e941-4fa5-bf62-d4bae2904a2d.png)
