### ISSUE TITLE
Menu responsiveness

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#55]
On mobile, the list items of the menu go all the way left. They should be right-aligned.
![image](https://user-images.githubusercontent.com/9844254/137585442-8e2a1027-1047-491d-af84-6115a222da88.png)

**Comment by Sidben99** [comment]
Is this what is required?
![Screenshot from 2021-10-16 22-07-46](https://user-images.githubusercontent.com/75398311/137602220-263d709f-9636-4e47-b2a9-4d28455a49e4.png)

**Comment by AhsanAyaz** [comment]
> Is this what is required? ![Screenshot from 2021-10-16 22-07-46](https://user-images.githubusercontent.com/75398311/137602220-263d709f-9636-4e47-b2a9-4d28455a49e4.png)

Yes, exactly @Sidben99 .
I assigned the issue to you
