### ISSUE TITLE
Instead of clicking the user name, we should have a GitHub icon for user profile

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#56]
Right now, when we click on a user name in the user profile page (for example [https://codewithahsan.org/people/ahsanayaz](https://codewithahsan.org/people/ahsanayaz)), it opens a new tab with the user's github username.
we should rather have a GitHub icon for this. As shown below

![image](https://user-images.githubusercontent.com/9844254/137585541-aa66f017-87bb-41d0-bf5f-3c1971af66e7.png)

**Comment by RajputUsman** [comment]
@AhsanAyaz Could you assign this to me?
