### ISSUE TITLE
Banner image broken for GitHub readme and in siteMetadata.js

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#84]
**Describe the bug**
The banner image in the readme is broken. And so is in the `siteMetadata.js`

**Expected behavior**
The github readme should show the correct banner image. And the siteMetadata should be fixed as well

**Additional context**
The banner image was renamed to `banner_old.png`. So we can either rename it back to `banner.png` or fix the URLs in the readme and in the `siteMetada.js`. 
I would prefer renaming the file back to `banner.png`.

**Comment by ahmedgadit** [comment]
Hey @AhsanAyaz Imohib mirza made changes to this issue can you please verify this push request 

#85

**Comment by AhsanAyaz** [comment]
closed by #85 
Thanks @ahmedgadit
