### ISSUE TITLE
Wrong GDE profile link

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#89]
**Describe the bug**
Currently, codewithahsan.dev/gde ends up in [this link](https://developers.google.com/community/experts/directory), whereas it should point to [https://g.dev/ahsanayaz](https://g.dev/ahsanayaz)

**To Reproduce**
1. Go to [the website](https://www.codewithahsan.dev/)
2. Click on 'Google Developers Expert in Angular' link

**Expected behavior**
It should redirect to [https://g.dev/ahsanayaz](https://g.dev/ahsanayaz)

**Comment by Jahan-Shah** [comment]
I'm picking it

**Comment by blazenn2** [comment]
Please assign it to me

**Comment by Jahan-Shah** [comment]
this issue is resolved here #93

**Comment by AhsanAyaz** [comment]
Closed by #93
