### ISSUE TITLE
Better auto-generated thumbnails for missing thumbnails for blog posts

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#90]
**Is your feature request related to a problem? Please describe.**
We have a [meta-placeholder.png](https://www.codewithahsan.dev/static/images/meta-placeholder.png) which is super ugly. And when we run the script `scripts/custom/generate-thumbnails.js`, it generates an ugly thumbnail as well.

**Describe the solution you'd like**
A better placeholder image for the script to use. It needs to be plain. Should contain enough space for the image title, and should contain just my image from my GitHub avatar.

The whole thumbnail will only have the following:
- Plain background
- Title of the blog post
- My image

Once you've updated the image, do the following to test it out:
- delete some of the `seo.jpg` files from `public/static/images` folder (files are further inside the blog post folders)
- run `npm run generate:thumbnails` to generate the missing thumbnails
- verify the thumbnails
- Add a screenshot to your PR

**Comment by zainbinfurqan** [comment]
@AhsanAyaz Can I work on this issue?

**Comment by AhsanAyaz** [comment]
@zainbinfurqan this has been fixed by #96

**Comment by AhsanAyaz** [comment]
@zainbinfurqan Sorry but this doesn't look good.
![image](https://github.com/AhsanAyaz/code-with-ahsan/assets/9844254/a65661a6-4624-45cb-af44-1e2d23fb4367)

Reopening it to be fixed. Please include a screenshot in the PR to try with different thumbnails. I've added more instructions in the ticket's description

**Comment by AhsanAyaz** [comment]
Closed by #100
