### ISSUE TITLE
Submissions: Make every card of similar width

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#91]
**Describe the bug**
Some of the cards on the submission page seem smaller than the others. The idea is to have similar sized cards for all the submissions.

**To Reproduce**
1. Go to [this page](https://www.codewithahsan.dev/courses/web-dev-basics/submissions)
2. See the different sized cards

**Expected behavior**
All cards should have the same width

**Screenshots**
![image](https://github.com/AhsanAyaz/code-with-ahsan/assets/9844254/ea1fa55e-f9cc-4b2d-be67-d51aabf7c853)

**Comment by Jahan-Shah** [comment]
issue resolved by #98

**Comment by AhsanAyaz** [comment]
Closed by #98

**Comment by Jahan-Shah** [comment]
it's not resolved yet. The PR was drafted
