### ISSUE TITLE
About: Change company title to SALT

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/code-with-ahsan#92]
**Describe the bug**
Currently, the company shown on the about page is Syncron AB

**To Reproduce**
1. Go to [the about page](https://www.codewithahsan.dev/about) 
2. See the profile card
3. See Syncron AB

**Expected behavior**
It should rather say SALT

**Screenshots**
![image](https://github.com/AhsanAyaz/code-with-ahsan/assets/9844254/b2a418ae-f301-48e2-9caf-10c20966e8b5)

**Comment by akssshh** [comment]
Hey @AhsanAyaz Can you assign this to me?

**Comment by AhsanAyaz** [comment]
@akssshh done
